Development
dpak1999/Mini-Project-4-NotesApp pull request #1
Opened 2020-12-17 15:23 UTC by dpak1999

@sagarchoudhary96 review 🙂🙂🙂

2020-12-19 13:51 UTC, sagarchoudhary96 requested changes

2020-12-19 13:51 UTC, sagarchoudhary96 commented on src/Components/ModalComponent.js
> +      <Modal
Please refactor this as discussed,  Modal is something that opens up as a dialog In your case on click of add task you are opening modal which should just have the form and the list should ideally be outside the modal in your home component.

2020-12-19 13:51 UTC, sagarchoudhary96 commented on src/Components/NotesList.js
> +      <Col md={6} key={Math.random()}>
don't use `Math.random()` as key instead while creating a note, add a 'note_id' by yourself to note object. which can be a unique id for each note. you can use https://www.npmjs.com/package/uuid package

2020-12-19 19:17 UTC, dpak1999 commented
@sagarchoudhary96  review please

2020-12-24 12:43 UTC, sagarchoudhary96 requested changes

2020-12-24 12:43 UTC, sagarchoudhary96 commented on src/Components/HomeComponent.js
> +  }, [searchItem]);
you need to split this hook into too. 

1. componentDidMount lifecycle --> it should have the part to get data from localStorage and update result and notes arr with same data.

2. useEffect with dependency on searchItem -> this should have the logic to filter notes based on search item.

2020-12-24 12:43 UTC, sagarchoudhary96 commented on src/Components/HomeComponent.js
> +        <NotesList notes={notes} />
same notesList component can be used here right, not need to create searchResults component. you can just pass `notes={results}` to your component.

2020-12-24 12:43 UTC, sagarchoudhary96 commented on src/Components/SearchResults.js
> +import React from "react";
this whole component can be removed.

2020-12-25 15:57 UTC, dpak1999 commented
@sagarchoudhary96  done refactoring

2020-12-27 04:02 UTC, merged

2020-12-27 04:41 UTC, sagarchoudhary96 reviewed
Looks good now